### ISSUE TITLE
Missing Implementation

### ISSUE THREAD

**Issue by devggm** [ancon-labs/react-native-adyen-dropin#10]
Hi Buddy,

Thanks a lot for this work when Adyen's official Lib is not available, really appreciate it.

When I was integrating your lib with my project, I found that some implementation is missing.

Below is the list of missing implementation:

1. reference : You forgot to add reference, which is mandatory for Adyen payments api.
2. paywithgoogle : You have not implemented Google Pay.

For now, I was able to found above two points. Will share more if found any.

I have fixed these issues in my local system, let me know if you want me to create a PR.

**Comment by jesperjohansson** [comment]
Hello @devggm, It depends on how your implementation looks like, we use `reference` in our server side. Yes, please do! 👍

**Comment by devggm** [comment]
Hi @jesperjohansson,

Well, I have made some changes as per my requirement, and published the
library. So, I would prefer keep it separate so that if anyone require
those changes he can install that one.

Link to my updated lib -> https://www.npmjs.com/package/@devggm/react-native-adyen-dropin

Thanks, to you once again for creating this lib. It really helped me a lot.

Best Regards,
Pankaj Mundra
