### ISSUE TITLE
Getting blank "Payment Methods" modal.

### ISSUE THREAD

**Issue by Napster2210** [ancon-labs/react-native-adyen-dropin#11]
Hello @jesperjohansson , While I am initiating the Adyen Drop In module I am getting below blank modal UI:

![image](https://user-images.githubusercontent.com/17761063/194785438-4a494ecb-cb2e-4424-9c80-5c6eebe604c6.png)

In Xcode logger I am getting last log as "Called start" message. Can you please help me out with this? I am not able to proceed further.

**Comment by Napster2210** [comment]
My paymentMethods API response:

```json
{"groups":null,"oneClickPaymentMethods":null,"paymentMethods":[{"brand":null,"brands":["amex","mc","visa"],"configuration":null,"issuers":null,"fundingSource":null,"group":null,"inputDetails":null,"name":"Credit Card","type":"scheme"}],"storedPaymentMethods":null,"storingMethods":null}
```

**Comment by Napster2210** [comment]
Cc @mortend

**Comment by mortend** [comment]
@Napster2210 FWIW, our app is still on version 1.5.2 of this module and works fine. Haven't tried later versions yet.

**Comment by jesperjohansson** [comment]
Hello @Napster2210, have you tried cloning the repo and running the example app? Do you get the same issue there? May be related to the payment methods response format.

**Comment by Napster2210** [comment]
Thanx @jesperjohansson Got the issue, there are some `null` fields in paymentMethods object which cause the issue.
