### ISSUE TITLE
Android: Invariant Violation: requireNativeComponent: "AdyenDropIn" was not found in the UIManager.

### ISSUE THREAD

**Issue by Napster2210** [ancon-labs/react-native-adyen-dropin#12]
Hello @jesperjohansson @mortend  I am getting this specific error for Android. Below are my logs:

adb logcat

10-14 02:53:24.329 12079 12119 D EGL_emulation: app_time_stats: avg=231.98ms min=2.97ms max=8388.39ms count=37
10-14 02:53:26.035 12079 12119 D EGL_emulation: app_time_stats: avg=23.22ms min=3.17ms max=812.85ms count=46
10-14 02:53:26.880 12079 12079 I ReactNative: [GESTURE HANDLER] Tearing down gesture handler registered for root view com.facebook.react.ReactRootView{4dd532c V.E...... ......ID 0,0-1080,2082 #1}
10-14 02:53:26.888   701   924 D EGL_emulation: app_time_stats: avg=2686.11ms min=14.25ms max=26363.93ms count=10
10-14 02:53:27.005   524   682 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10147; state: DISABLED
10-14 02:53:27.012   329   382 D goldfish-address-space: claimShared: Ask to claim region [0x1f1a44000 0x1f23ac000]
10-14 02:53:27.014   329   382 D goldfish-address-space: claimShared: Ask to claim region [0x1f2c0c000 0x1f3574000]
10-14 02:53:27.014   329   382 D goldfish-address-space: claimShared: Ask to claim region [0x1f3574000 0x1f3edc000]
10-14 02:53:27.042  1251  1251 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3420 
10-14 02:53:27.042  1251  1251 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():2002 
10-14 02:53:27.042  1251  1251 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():31 Notify device unlocked.
10-14 02:53:27.089 12079 12079 E unknown:FabricViewStateManager: setState called without a StateWrapper
10-14 02:53:28.684 12079 12119 D EGL_emulation: app_time_stats: avg=73.30ms min=2.68ms max=1245.14ms count=19

Do you guys have any idea about this issue?
![image](https://user-images.githubusercontent.com/17761063/195713950-431cd563-b3a5-473d-bd64-ce31f9343850.png)

**Comment by jesperjohansson** [comment]
Hello @Napster2210, I don't think I have seen this error before 🤔 Which version of RN ar you running? Make sure you have followed all of the Android setup instructions from the readme.

**Comment by jesperjohansson** [comment]
Are you using `AdyenDropIn` as a view? Like `<AdyenDropIn />`? If so use the new method instead: https://github.com/ancon-labs/react-native-adyen-dropin#usage

**Comment by Napster2210** [comment]
Thanx @jesperjohansson
